# Generated by Django 3.2.9 on 2021-11-25 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srf_id', models.BigIntegerField(unique=True, verbose_name='SRF ID')),
                ('ref_by', models.CharField(max_length=64, verbose_name='Ref .By')),
                ('lab_id', models.IntegerField(verbose_name='LAB ID')),
                ('printed', models.DateTimeField(default=datetime.datetime.now)),
                ('sample_collection', models.DateTimeField(default=datetime.datetime.now, verbose_name='Sample Collection')),
                ('sample_received', models.DateTimeField(default=datetime.datetime.now, verbose_name='Sample Received')),
                ('report_released', models.DateTimeField(default=datetime.datetime.now, verbose_name='Report Release')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of_sample', models.TextField(verbose_name='Type of Sample')),
                ('sample_condition_of_receipt', models.CharField(max_length=124, verbose_name='Sample Condition of Receipt')),
                ('pcr_kit', models.CharField(max_length=64, verbose_name='PCR Kit')),
                ('n_gene', models.CharField(max_length=64, verbose_name='N gene')),
                ('rdrp_gene', models.CharField(max_length=64, verbose_name='RdRP gene')),
                ('rtpcr_test', models.BooleanField(default=False, verbose_name='SARS-CoV2 (COVID-19) RT PCR Test result')),
                ('equipment', models.CharField(max_length=64, verbose_name='Equipment')),
            ],
        ),
    ]
