# Generated by Django 3.2.9 on 2021-11-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RtpcTestReportApp', '0002_patientreport_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='e_gene',
            field=models.CharField(default=123, max_length=64, verbose_name='E gene'),
            preserve_default=False,
        ),
    ]
