# Generated by Django 3.2.9 on 2021-11-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RtpcTestReportApp', '0003_patientreport_e_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='rtpcr_test',
            field=models.BooleanField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='Negative', verbose_name='SARS-CoV2 (COVID-19) RT PCR Test result'),
        ),
    ]
