# Generated by Django 3.2.9 on 2021-11-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RtpcTestReportApp', '0007_alter_patientreport_rtpcr_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='rtpcr_test',
            field=models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=10, verbose_name='SARS-CoV2 (COVID-19) RT PCR Test result'),
        ),
    ]
